version: "3.7"

services:
  server:
    image: nginx:alpine
    container_name: ${CONTAINER_PREFIX}_server
    working_dir: /var/www/chatbot
    volumes:
      - ./application:/var/www/chatbot
      - ./.docker/images/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - chatbot

  php-fpm:
    build: .docker/images/php-fpm
    container_name: ${CONTAINER_PREFIX}_php-fpm
    working_dir: /var/www/chatbot
    volumes:
      - ./application:/var/www/chatbot
      - ./.docker/images/php-fpm/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - chatbot

networks:
  chatbot:
    driver: "bridge"